deploy:
  stage: build
  only:
    - test
  script:
    - git branch -vv
    - git pull origin test:test
    - docker exec matrix_about rm -rf /usr/share/nginx/html
    - docker cp src/. matrix_about:/usr/share/nginx/html
