version: '2'

services:
  matrix_about:
    build: .
    image: about-nginx
    ports:
      - 8100:80
    command: nginx -g 'daemon off;'
    container_name: about
    volumes:
      - /var/log/nginx:/var/log/nginx
    restart: always

