version: '2'

services:
  matrix_about:
    build: .
    image: about-nginx
    ports:
      - 8100:80
    command: nginx -g 'daemon off;'
    container_name: matrix_about
    environment:
      - LANG=C.UTF-8
    volumes:
      - /home/matrix/about/volume:/usr/share/nginx/html
      - /var/log/nginx/about:/var/log/nginx
    restart: always
